USE burgers_db;

CREATE TABLE burgers(
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    burger_name VARCHAR(30),
    devoured BOOLEAN DEFAULT False,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
